Add TextExtract Kotlin sample
datalogics/apdfl-kotlin-samples pull request #1
Opened 2024-01-11 21:52 UTC by datalogics-saharay

Let's add a Kotlin sample that shows how to extract text from tagged and untagged PDF documents using the Java Maven APDFL package!

**No Jira issue**

2024-01-11 21:55 UTC, datalogics-robb approved these changes

2024-01-15 20:18 UTC, datalogics-robl requested changes
My only suggestions are formatting issues and possibly a wrong name in the comments.

2024-01-15 20:18 UTC, datalogics-robl commented on TextExtract/src/main/kotlin/com/datalogics/pdfl/samples/TextExtract.kt
> +    }finally {
Is there a coding standard for Kotlin that covers spacing, indentation, etc.? The uneven spacing around the `finally` keyword really stands out here.

More generally, samples should have on their best formal wear, so we should really get the details right: for example, note the space after `if` on line 77 versus the lack thereof on lines 49-50-51.

Really, I'm advocating for finding a Kotlin linter/formatter and running this sample through it.

2024-01-15 20:18 UTC, datalogics-robl commented on TextExtract/src/main/kotlin/com/datalogics/pdfl/samples/TextExtract.kt
> +* the text is produced using standard Times Roman encoding. The program is also written
I see we copied this from another sample, but I question if "Times Roman" is the right term. "Times Roman" is a font; "Roman" is an encoding, more or less a synonym for "Latin", and is probably what is meant.

2024-01-16 23:13 UTC, datalogics-saharay commented on TextExtract/src/main/kotlin/com/datalogics/pdfl/samples/TextExtract.kt
> +    }finally {
Good suggestion, done! Luckily, IntelliJ had a built-in Kotlin formatter: https://discuss.kotlinlang.org/t/kotlin-code-auto-format/407.

2024-01-16 23:13 UTC, datalogics-saharay commented on TextExtract/src/main/kotlin/com/datalogics/pdfl/samples/TextExtract.kt
> +* the text is produced using standard Times Roman encoding. The program is also written
Fixed

2024-01-17 17:22 UTC, datalogics-robl approved these changes

2024-01-17 17:22 UTC, merged